Fixes #135 - Fix rendering of buttons in header
mybbgroup/Isango pull request #137
Opened 2021-02-12 20:56 UTC by Eldenroot

Use global_start instead of global_end  hook to render buttons in header.

Fixes #135 

**Thank you @lairdshaw for debugging and for your fix!**

2021-02-12 20:58 UTC, effone commented
As much I can remember I used global start only for templates as well as buttons...
I am so lost.
On Feb 13, 2021, 2:27 AM +0530, Eldenroot <notifications@github.com>, wrote:
> Use global_start instead of global_end hook to render buttons in header.
> Fixes #135
> Thank you @lairdshaw for debugging and for your fix!
> You can view, comment on, or merge this pull request online at:
> https://github.com/mybbgroup/Isango/pull/137
> Commit Summary
>
> • Fixes #135 - Use global_start instead of global_end hook to render buttons in header
>
> File Changes
>
> • M upload/inc/plugins/isango.php (2)
>
> Patch Links:
>
> • https://github.com/mybbgroup/Isango/pull/137.patch
> • https://github.com/mybbgroup/Isango/pull/137.diff
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-12 21:21 UTC, lairdshaw commented
> As much I can remember I used global start only for templates as well as buttons...

Looks like you switched to global end for buttons 17 days ago in commit 4106193fc3a1643a10234f11c5d7944f36e88bbc "Input loader hook change". Not sure what motivated that change.

> I am so lost.

Oh, but you're on GitHub. You're home!

2021-02-12 21:22 UTC, lairdshaw approved these changes, later dismissed

2021-02-13 04:01 UTC, effone commented
Can't remember. Probably to cover the template caching...

We need to check further if the button templates are cached now and if not need to finetune the task sequence / priority as both templates and buttons are using same hook.

We can alternately think of triggering a single hook for template caching and call the button generation from inside template cache function after caching templates just to make sure about the process sequence.

2021-02-13 08:47 UTC, lairdshaw commented
Probably your suggestion is the way to go. Maybe have a single `global_start` hook called something like `isango_init()`, and from it call `isango_templates()` followed by `isango_buttons()`?

2021-02-13 08:48 UTC, lairdshaw commented
Ah, wait. That wouldn't ensure that templates are cached - they need to be cached in-between the calls. Now I see what probably motivated you to change the hook.

2021-02-13 08:52 UTC, lairdshaw commented
OK, it looks like instead of moving `isango_buttons` to the `global_start` hook, it would work if we moved it to the `global_intermediate` hook, which is called on line 494. That way it occurs after templates are cached on line 476,
but before the header is generated on line 958.

Yes?

2021-02-13 09:11 UTC, effone commented
> Yes?

There is a hook like that? Yes thats the good approach.

The nasty one would be call `isango_buttons()` from inside `isango_templates()` at the end, after caching templates.

2021-02-13 09:14 UTC, effone commented
Also to mention, the third parameter of `add_hook()` method is **priority**. 
Defining priority is another good approach too...

https://github.com/mybb/mybb/blob/feature/inc/class_plugins.php#L53

2021-02-13 09:32 UTC, effone commented
> Better is to add isango_buttons() to the global_intermediate hook than to the global_start hook.
Agreed.

2021-02-13 09:33 UTC, lairdshaw commented
> There is a hook like that? Yes thats the good approach.

I'm glad we're agreed. @Eldenroot, could you please update the PR so that we use the `global_intermediate` hook rather than `global_start`?

> The nasty one would be call `isango_buttons()` from inside `isango_templates()` at the end, after caching templates.

Mmm, but templates are only cached _after_ the `global_start` hook, on line 476 of global.php, so they aren't cached until _after_ `isango_templates()` runs.

> Defining priority is another good approach too...

Same problem as above: the templates are only cached _after_ `global_start`, so it wouldn't matter what priority the `global_start` hooks ran at - templates wouldn't be cached anyway.

2021-02-13 09:37 UTC, effone requested changes

2021-02-13 09:37 UTC, effone commented on upload/inc/plugins/isango.php
> +$plugins->add_hook('global_start', 'isango_buttons');
Please use `global_intermediate` as rightly suggested by @lairdshaw

2021-02-13 10:28 UTC, Eldenroot commented
Ok, I will edit it in 2 hoirs

2021-02-13 11:55 UTC, Eldenroot commented
OK, changed. Can we merge?

2021-02-13 11:57 UTC, effone approved these changes

2021-02-13 11:58 UTC, merged